[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.13"
aws-sdk-dynamodb = "1.59.0"
blake3 = "1.5.5"
lambda_http = "0.13.0"
percent-encoding = "2.3.1"
rand = "0.8.5"

tokio = { version = "1", features = ["macros"] }
